### ISSUE TITLE
Subviews misaligned

### ISSUE THREAD

**Issue by dimovskidamjan** [AfrozZaheer/AZCollectionViewController#4]
Why is it that all subviews, such as loading, no results, etc. are slightly offset to the right? This can also be seen in the example project, and happens with every method of loading those views - I've tried using accessory views in IB, setting a custom XIB class, or using the predefined ones and all of them are exhibiting the same problem.

**Comment by AfrozZaheer** [comment]
Well, I have been testing it on many devices including new XSMAX and XR I'm not facing the issue. If it still occurred can you please share video or picture?

**Comment by dimovskidamjan** [comment]
It's really easy to reproduce, just run the app on iPhone 8 Simulator and put a breakpoint on the `didFetchData` call. The result is this:
![simulator screen shot - iphone 8 - 2018-11-09 at 14 46 13](https://user-images.githubusercontent.com/9072054/48266023-6e012f00-e42e-11e8-8dba-8295560490b6.png)

As you can see, there is clearly a thin gray gap to the left and on top of the collection view, while such a gap is not visible to the right and on the bottom. This is the offset that I'm talking about.
